
#General
[general]
	#Enables ingame rewards on first spawn for Patreons
	patreon_rewards = true

#Collectibles
[collectibles]
	#How much xp a player should get when he finds a collectible
	#Range: 0 ~ 1000
	collectible_xp = 30
	#How rarely should coin collectibles drop. higher = rarer [1:X]
	#Range: 1 ~ 100000
	coin_collectibles_rarity = 2200
	#How rarely should fragment collectibles drop. higher = rarer [1:X]
	#Range: 1 ~ 100000
	fragment_collectibles_rarity = 2100
	#How rarely should fossil collectibles drop. higher = rarer [1:X]
	#Range: 1 ~ 100000
	fossil_collectibles_rarity = 1300

#Loot Bag
[loot_bag]
	#How much xp a player should get when he uses a loot bag
	#Range: 0 ~ 1000
	epic_loot_bag_xp = 100
	#A list with all epic loot bag rewards [amount*modid:item]
	epic_loot_bag_rewards = ["1*minecraft:netherite_ingot", "1*minecraft:totem_of_undying", "1*minecraft:enchanted_golden_apple", "5*minecraft:dragon_breath", "10*minecraft:diamond", "2*the_bumblezone:royal_jelly_bottle", "1*celestial_core:pillager_outpost_loot_box", "1*simplehats:hatbag_rare", "1*simplehats:hatbag_epic", "1*simplehats:hatbag_easter",  "1*celestial_core:shulker_scrap", "1*celestial_core:desert_pyramid_loot_box", "1*celestial_core:soaring_wings", "1*celestial_core:warden_sclerite", "1*apotheosis:boss_summoner", "1*apotheosis:epic_material",  "1*celestial_core:heart_fragment", "1*celestial_core:igloo_loot_box", "1*friendsandfoes:totem_of_illusion", "1*kubejs:coin_dungeon", "1*apotheosis:rare_material", "1*the_bumblezone:royal_jelly_bottle", "1*celestial_core:manson_loot_box", "1*friendsandfoes:totem_of_freezing", "1*simplehats:hatbag_festive", "1*simplehats:hatbag_halloween", "1*simplehats:hatbag_summer", "1*collectorsalbum:epic_card_pack", "1*collectorsalbum:rare_card_pack", "1*l2complements:soul_flame", "1*l2complements:totem_of_dream", "1*l2complements:sun_membrane", "1*embers:ancient_golem_spawn_egg", "20*minecraft:experience_bottle", "10*ars_nouveau:greater_experience_gem", "2*kubejs:scroll_exp_great", "1*aquaculture:neptunium_ingot", "1*apotheotic_additions:ascended_coin", "1*apotheotic_additions:infused_coin", "1*apotheotic_additions:artifact_material", "1*celestial_artifacts:purified_powder"]
	#How many item entries the epic loot bag gives the player
	#Range: 1 ~ 10
	epic_loot_bag_item_amount = 1
	#A list with all loot bag rewards [amount*modid:item]
	loot_bag_rewards = ["5*simplehats:hatscraps_common", "1*simplehats:hatscraps_rare", "5*apotheosis:gem_dust", "3*simplehats:hatscraps_uncommon", "3*apotheosis:uncommon_material", "1*simplehats:hatbag_common", "5*apotheosis:common_material", "1*simplehats:hatbag_uncommon", "6*aquaculture:treasure_chest", "1*apotheotic_additions:apotheotic_coin", "1*kubejs:scroll_exp", "10*ars_nouveau:experience_gem", "10*minecraft:experience_bottle", "1*collectorsalbum:common_card_pack", "1*collectorsalbum:uncommon_card_pack","3*minecraft:emerald", "3*minecraft:diamond", "1*minecraft:golden_apple", "1*minecraft:ender_eye"]
	#How much xp a player should get when he uses a loot bag
	#Range: 0 ~ 1000
	loot_bag_xp = 50
	#How many item entries the loot bag gives the player
	#Range: 1 ~ 10
	loot_bag_item_amount = 1

