#Cursed Doll spawn weight. Bigger number equals more common
#Range: > 1
cursedDollSpawnWeight = 40
#Cursed Doll min spawn count. Bigger number equals more common
#Range: > 1
cursedDollMinSpawnCount = 1
#Cursed Doll max spawn count. Bigger number equals more common
#Range: > 1
cursedDollMaxSpawnCount = 1
#Cursed Doll biome tag. This is where the mob will spawn
cursedDollBiomeTag = "is_overworld"
#Direwolf spawn weight. Bigger number equals more common
#Range: > 1
direwolfSpawnWeight = 20
#Direwolf min spawn count. Bigger number equals more common
#Range: > 1
direwolfMinSpawnCount = 3
#Direwolf max spawn count. Bigger number equals more common
#Range: > 1
direwolfMaxSpawnCount = 6
#Direwolf biome tag. This is where the mob will spawn
direwolfBiomeTag = "forge:plains"
#Haunt spawn weight. Bigger number equals more common
#Range: > 1
hauntSpawnWeight = 60
#Haunt min spawn count. Bigger number equals more common
#Range: > 1
hauntMinSpawnCount = 1
#Haunt max spawn count. Bigger number equals more common
#Range: > 1
hauntMaxSpawnCount = 4
#Haunt biome tag. This is where the mob will spawn
hauntBiomeTag = "is_forest"
#Meadow Slime spawn weight. Bigger number equals more common
#Range: > 1
meadowSlimeSpawnWeight = 50
#Meadow Slime min spawn count. Bigger number equals more common
#Range: > 1
meadowSlimeMinSpawnCount = 1
#Meadow Slime max spawn count. Bigger number equals more common
#Range: > 1
meadowSlimeMaxSpawnCount = 1
#Meadow Slime biome tag. This is where the mob will spawn
meadowSlimeBiomeTag = "has_structure/village_plains"
#Shade spawn weight. Bigger number equals more common
#Range: > 1
shadeSpawnWeight = 60
#Shade min spawn count. Bigger number equals more common
#Range: > 1
shadeMinSpawnCount = 1
#Shade max spawn count. Bigger number equals more common
#Range: > 1
shadeMaxSpawnCount = 1
#Shade biome tag. This is where the mob will spawn
shadeBiomeTag = "is_forest"
#Shroomin spawn weight. Bigger number equals more common
#Range: > 1
shroominSpawnWeight = 90
#Shroomin min spawn count. Bigger number equals more common
#Range: > 1
shroominMinSpawnCount = 1
#Shroomin max spawn count. Bigger number equals more common
#Range: > 1
shroominMaxSpawnCount = 5
#Shroomin biome tag. This is where the mob will spawn
shroominBiomeTag = "forge:taiga"
#Specter spawn weight. Bigger number equals more common
#Range: > 1
specterSpawnWeight = 40
#Specter min spawn count. Bigger number equals more common
#Range: > 1
specterMinSpawnCount = 1
#Specter max spawn count. Bigger number equals more common
#Range: > 1
specterMaxSpawnCount = 1
#Specter biome tag. This is where the mob will spawn
specterBiomeTag = "forge:is_underground"
#Sprite spawn weight. Bigger number equals more common
#Range: > 1
spriteSpawnWeight = 10
#Sprite min spawn count. Bigger number equals more common
#Range: > 1
spriteMinSpawnCount = 3
#Sprite max spawn count. Bigger number equals more common
#Range: > 1
spriteMaxSpawnCount = 5
#Sprite biome tag. This is where the mob will spawn
spriteBiomeTag = "is_forest"
#Vengeful Gravestone spawn weight. Bigger number equals more common
#Range: > 1
vengefulGravestoneSpawnWeight = 65
#Vengeful Gravestone min spawn count. Bigger number equals more common
#Range: > 1
vengefulGravestoneMinSpawnCount = 1
#Vengeful Gravestone max spawn count. Bigger number equals more common
#Range: > 1
vengefulGravestoneMaxSpawnCount = 1
#Vengeful Gravestone biome tag. This is where the mob will spawn
vengefulGravestoneBiomeTag = "forge:is_underground"
#Wandering Lantern spawn weight. Bigger number equals more common
#Range: > 1
wanderingLanternSpawnWeight = 20
#Wandering Lantern min spawn count. Bigger number equals more common
#Range: > 1
wanderingLanternMinSpawnCount = 1
#Wandering Lantern max spawn count. Bigger number equals more common
#Range: > 1
wanderingLanternMaxSpawnCount = 1
#Wandering Lantern biome tag. This is where the mob will spawn
wanderingLanternBiomeTag = "is_overworld"
#Will O Wisp spawn weight. Bigger number equals more common
#Range: > 1
willOWispSpawnWeight = 30
#Will O Wisp min spawn count. Bigger number equals more common
#Range: > 1
willOWispMinSpawnCount = 1
#Will O Wisp max spawn count. Bigger number equals more common
#Range: > 1
willOWispMaxSpawnCount = 1
#Will O Wisp biome tag. This is where the mob will spawn
willOWispBiomeTag = "is_forest"

