
#Configuration file for player states.
#You can adjust stamina delta (negative value means consumption / positive value means gain) and
#recovery delay (in ticks) of all player states registered in the game.
#To reload the config, use the following command: /paraglider reloadPlayerStates
#
[paraglider]

	[paraglider.ascending]
		#Range: > -2147483648
		staminaDelta = -6
		#Range: > 0
		recoveryDelay = 10

	[paraglider.breathing_underwater]
		#Range: > -2147483648
		staminaDelta = 0
		#Range: > 0
		recoveryDelay = 10

	[paraglider.flying]
		#Range: > -2147483648
		staminaDelta = 5
		#Range: > 0
		recoveryDelay = 10

	[paraglider.idle]
		#Range: > -2147483648
		staminaDelta = 75
		#Range: > 0
		recoveryDelay = 0

	[paraglider.midair]
		#Range: > -2147483648
		staminaDelta = -5
		#Range: > 0
		recoveryDelay = 0

	[paraglider.on_vehicle]
		#Range: > -2147483648
		staminaDelta = 20
		#Range: > 0
		recoveryDelay = 10

	[paraglider.panic_paragliding]
		#Range: > -2147483648
		staminaDelta = -3
		#Range: > 0
		recoveryDelay = 10

	[paraglider.paragliding]
		#Range: > -2147483648
		staminaDelta = -10
		#Range: > 0
		recoveryDelay = 20

	[paraglider.running]
		#Range: > -2147483648
		staminaDelta = -3
		#Range: > 0
		recoveryDelay = 20

	[paraglider.swimming]
		#Range: > -2147483648
		staminaDelta = -10
		#Range: > 0
		recoveryDelay = 20

	[paraglider.underwater]
		#Range: > -2147483648
		staminaDelta = 15
		#Range: > 0
		recoveryDelay = 0

	[paraglider.breakfall]
		#Range: > -2147483648
		staminaDelta = -20
		#Range: > 0
		recoveryDelay = 10

	[paraglider.cat_leap]
		#Range: > -2147483648
		staminaDelta = -15
		#Range: > 0
		recoveryDelay = 10

	[paraglider.charge_jump]
		#Range: > -2147483648
		staminaDelta = -15
		#Range: > 0
		recoveryDelay = 10

	[paraglider.climb_up]
		#Range: > -2147483648
		staminaDelta = -10
		#Range: > 0
		recoveryDelay = 10

	[paraglider.cling_to_cliff]
		#Range: > -2147483648
		staminaDelta = -5
		#Range: > 0
		recoveryDelay = 10

	[paraglider.dodge]
		#Range: > -2147483648
		staminaDelta = -15
		#Range: > 0
		recoveryDelay = 10

	[paraglider.fast_running]
		#Range: > -2147483648
		staminaDelta = -15
		#Range: > 0
		recoveryDelay = 10

	[paraglider.fast_swimming]
		#Range: > -2147483648
		staminaDelta = -15
		#Range: > 0
		recoveryDelay = 10

	[paraglider.horizontal_wall_run]
		#Range: > -2147483648
		staminaDelta = -10
		#Range: > 0
		recoveryDelay = 10

	[paraglider.roll]
		#Range: > -2147483648
		staminaDelta = -15
		#Range: > 0
		recoveryDelay = 10

	[paraglider.vault]
		#Range: > -2147483648
		staminaDelta = -12
		#Range: > 0
		recoveryDelay = 10

	[paraglider.vertical_wall_run]
		#Range: > -2147483648
		staminaDelta = -12
		#Range: > 0
		recoveryDelay = 10

