
["Alt Textures"]
	#Texture for Soluna Blade
	#Range: 0 ~ 1
	styleSolunaBlade = 0
	#Texture for Scorpion Blade
	#Range: 0 ~ 3
	styleScorpionBlade = 0
	#Texture for Starhawk
	#Range: 0 ~ 1
	styleStarhawk = 0
	#Texture for Power Pole
	#Range: 0 ~ 1
	stylePowerPole = 0
	#Texture for Kalos
	#Range: 0 ~ 1
	styleGunblade = 0
	#Texture for Thundercracker
	#Range: 0 ~ 1
	styleLightningHammer = 0
	#Texture for Revenant's Edge
	#Range: 0 ~ 1
	styleRevenantsEdge = 0

